[build]
command = "make web"
publish = "build/public/web/"

[build.environment]
NODE_ENV = "production"
NODE_VERSION = "14"

[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = true

[build.processing.js]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[[plugins]]
package = "netlify-plugin-inline-critical-css"
